// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZPku5Cn15S15W786FQf_zCVDD6XOZQ3Y',
    appId: '1:334129958090:web:64edd3439bf2e89267f833',
    messagingSenderId: '334129958090',
    projectId: 'my-memory-project-52eab',
    authDomain: 'my-memory-project-52eab.firebaseapp.com',
    storageBucket: 'my-memory-project-52eab.appspot.com',
    measurementId: 'G-1W9C5DY0CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVBnffvzJJ2do4F2uWUY2wSSmv6KVRKu8',
    appId: '1:334129958090:android:81b74ff2720c9f7167f833',
    messagingSenderId: '334129958090',
    projectId: 'my-memory-project-52eab',
    storageBucket: 'my-memory-project-52eab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJQyiwn7wR2IId3If9UX7w-FPhxEDIOv0',
    appId: '1:334129958090:ios:7aa6a3078b14d51867f833',
    messagingSenderId: '334129958090',
    projectId: 'my-memory-project-52eab',
    storageBucket: 'my-memory-project-52eab.appspot.com',
    iosClientId: '334129958090-r9giea85k672uk9h2b07m90rmg89n73q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJQyiwn7wR2IId3If9UX7w-FPhxEDIOv0',
    appId: '1:334129958090:ios:7aa6a3078b14d51867f833',
    messagingSenderId: '334129958090',
    projectId: 'my-memory-project-52eab',
    storageBucket: 'my-memory-project-52eab.appspot.com',
    iosClientId: '334129958090-r9giea85k672uk9h2b07m90rmg89n73q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );
}
